import Navigation from "./components/Navigation";
import "./globals.css";
export const metadata = {
  title: "Assignment 2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body >{children}</body>
    </html>
  );
}
